### ISSUE TITLE
Constant spamming of "Request textDocument/X" failed while navigating through core.clj

### ISSUE THREAD

**Issue by Vatyx** [BetterThanTomorrow/calva#2276]
Completely new to clojure and I have just installed lein and calva on windows. As I scroll through core.clj vs code constantly gives me error notifications like so:
![image](https://github.com/BetterThanTomorrow/calva/assets/7674163/e398e373-4695-4ccd-a741-32fb49cfe696)

Here is some of the output log
```
[Error - 5:18:58 PM] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 5:18:59 PM] Request textDocument/semanticTokens/range failed.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 5:19:00 PM] Request textDocument/semanticTokens/range failed.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 5:19:00 PM] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603 
[object Object]
```

Is there any way to mute this or is something misconfigured?

**Comment by PEZ** [comment]
Hello. I'm sorry you're having this spamming! I don't know what's going on, but I suspect it could be a misconfiguration. Unfortunately Calva can't suppress those messages, so we will need to try figure out how to fix the configuration.

Can you describe your setup a bit more? Where is this `core.clj` file you are scrolling through? Is it in a project?

**Comment by PEZ** [comment]
@ericdallo, I think we need some handle for controlling these error messages. Maybe they could be reported some other way by default?

**Comment by Vatyx** [comment]
Sorry, you can see just how new to Clojure I am! I was scrolling through the core.clj of the clojure namespace. So the file that defines `let`, `defn`, etc.

For some more information, I used this guide to get started https://gist.github.com/bpringe/4f1d07f98633a956a8b33af572e7b810 and then simply hit F12 on `ns` to start reading that clojure/core.clj

**Comment by Vatyx** [comment]
I just installed my first dependency in my project.
* I tried navigating to a symbol defined in that dependency and Calva was unable to find the symbol.
* I restarted VS Code and then Calva was able to navigate me but now I am getting the same error spam as I got in clojure/core.clj

Additionally, when I am inside this dependency file, let's call it foo.clj, and it references a symbol defined in bar.clj, F12 does not work. However if I reference that symbol in my own core.clj file and then hit F12, it does take me to bar.clj. 

Edit: Upon more testing of the behavior above, it seems random now. Upon restarting again I can't go to closure/core.clj symbols from my core.clj file but if I go into the dependency, it can navigate.

**Comment by Vatyx** [comment]
So I decided to dive into Calva and debugged the issue! https://github.com/clojure-lsp/clojure-lsp/pull/1648

I'm not sure how to go about this second issue where I can't navigate to symbols that I definitely should be able to. the language server logs doesn't emit anything when it can't find the symbol

**Comment by ericdallo** [comment]
AFAICS it's some issue with your project configuration or so since those requests should not fail unless a bug in clojure-lsp, would be nice to get the server logs to check if there is any exception happening in clojure-lsp

@PEZ unfortunately there's nothing to do in the server side as they are really failing, the UI should be totally configurable in the client side, I suggest you open an issue in vscode-language-client plugin to support customize those things

**Comment by Vatyx** [comment]
Hey @ericdallo you may have not seen but there was indeed an error in clojure-lsp. I linked my PR for the fix above

**Comment by ericdallo** [comment]
Ah got it, thanks, will take a look

**Comment by PEZ** [comment]
> For some more information, I used this guide to get started https://gist.github.com/bpringe/4f1d07f98633a956a8b33af572e7b810 and then simply hit F12 on `ns` to start reading that clojure/core.clj

@bpringe, since you are the author of that guide, can you try reproduce the issues here?

**Comment by PEZ** [comment]
> @bpringe, since you are the author of that guide, can you try reproduce the issues here?

I now realize that @Vatyx and @ericdallo are [fixing the problem causing this batch of error message spamming](https://github.com/clojure-lsp/clojure-lsp/pull/1648). I guess the remaining issue is why the code navigation is acting up.

**Comment by ericdallo** [comment]
I think the navigation could be related with the clojure-lsp issue as well, maybe @Vatyx can confirm if that is fixed with the proposed fix?

**Comment by PEZ** [comment]
If it is, then there is a Calva issue too, because it should fall back on the REPL (or, assuming defaults, actually start with the REPL).

**Comment by bpringe** [comment]
@Vatyx Did you have a repl started and connected while you had that navigation issue?

(Also, I'm glad you found my guide useful. And great job on finding that clojure-lsp issue!)

**Comment by Vatyx** [comment]
I'm sorry for the delay. I've had a busy week. @bpringe thanks for the guide!

The navigation issue seemed unrelated to whether or not I was connecting to the repl or not. I was trying to debug the LSP to see if I could figure anything out but was having difficulty figuring it out 😂

**Comment by bpringe** [comment]
From Eric:

> I think the navigation could be related with the clojure-lsp issue as well, maybe @Vatyx can confirm if that is fixed with the proposed fix?

@Vatyx Is your navigation issue fixed by [your clojure-lsp changes](https://github.com/clojure-lsp/clojure-lsp/pull/1648)?

**Comment by Vatyx** [comment]
Hey @bpringe! I am still getting the navigation issue but it's very strange. So for example I have the clojure-lsp project open. I can navigate just fine afaict inside the project. I then want to navigate to something like the `testing` macro or `defn` or `async/take!`. These symbols will navigate fine but then navigation breaks inside that file. Maybe it's because those files are outside the clojure-lsp project? I have the REPL running as well.

**Comment by bpringe** [comment]
@Vatyx Hmm. With just clojure-lsp running and no repl connection, I can reproduce your issue (and maybe that's expected with clojure-lsp's navigation functionality - I'm not sure). With a repl connected, however, I can navigate to `defn`, and then from that file I can navigate to `fn`.

What's this setting set to for you?

![image](https://github.com/BetterThanTomorrow/calva/assets/12722744/37817454-6cf7-414c-b161-f1b77d02963f)
